const { type } = require('os')

describe('login', () => {
  beforeEach(() => {
    cy.visit('/index.html')
  })
  it('clicks login button', () => {
    cy.wait(2000)
    cy.get('.modal-footer button[data-auth="login"]').click()
    cy.wait(2000)
    cy.get('#loginEmail')
      .type('PetMik64782@stud.noroff.no')
      .should('have.value', 'PetMik64782@stud.noroff.no')
    cy.get('#loginPassword').type('testtest').should('have.value', 'testtest')
    cy.get(`button[type="submit"]`).contains('Login').click()
    cy.wait(2000)
    cy.get('.profile-email').contains('PetMik64782@stud.noroff.no')
  })
  it('logout', () => {
    cy.wait(2000)
    cy.get('.modal-footer button[data-auth="login"]').click()
    cy.wait(2000)
    cy.get('#loginEmail')
      .type('PetMik64782@stud.noroff.no')
      .should('have.value', 'PetMik64782@stud.noroff.no')
    cy.get('#loginPassword').type('testtest').should('have.value', 'testtest')
    cy.get(`button[type="submit"]`).contains('Login').click()
    cy.wait(2000)
    cy.get(`button[data-auth="logout"]`).click()
    cy.wait(2000)
    cy.get('#registerModalLabel')
    cy.timeout(2000).should('be.visible')
  })
})
