env:
  browser: true
  commonjs: true
  es2021: true
extends: eslint:recommended
overrides:
  - files: 
      - "**/*.test.js"
      - "**/*.mock.js" 
    env:
      jest: true
    plugins: ["jest"]
    extends: ["plugin:jest/recommended"]
    rules:
      jest/prefer-expect-assertions: "off"
  - files:
      - "**/*.cy.js"
    env:
      cypress/globals: true
    plugins:
      - cypress
    extends:
      - "plugin:cypress/recommended"
    rules:
      cypress/no-unnecessary-waiting: "off"
      no-unused-vars: "off"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
rules: {}
