name: Run Prettier, ESLint and Jest on commit
on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Prettier
        run: npm run format
