name: Code Review & Deploy to GitHub Pages

# Triggers
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches: ["workflow"]
  workflow_dispatch:

# Permissions
permissions:
  contents: read
  pull-requests: write
  pages: write
  id-token: write

jobs:
  # Code Review Job
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: fluxninja/openai-pr-reviewer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
  # Deployment Job
  deploy:
    # Only run this job on pushes to the workflow branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/workflow'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
