name: Code Review & Deploy to GitHub Pages

# Triggers
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches: ["workflow"]
  workflow_dispatch:

# Permissions
permissions:
  contents: read
  pull-requests: write
  pages: write
  id-token: write

jobs:
  # Code Review Job
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: fluxninja/openai-pr-reviewer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
  # Deployment Job
  deploy:
    # Only run this job on pushes to the workflow branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/workflow'
    runs-on: ubuntu-latest
    env:
      GH_PAGES_URL: 'https://ramtinmoshtagh.github.io/social-media-client/'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: npm i
        
      - name: Build SASS
        run: npm run build
        

      #- name: Setup Pages
      #  uses: jrandiny/apt-repo-action@v1
      #  with:
      #    ... (the appropriate inputs from the action's documentation)
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: '.'  # This uploads the entire current directory as an artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
        
    environment:
      name: github-pages
      url: ${{ env.GH_PAGES_URL }}
