# Runs on pushes targeting the default branch
name: AUTO - E2E Testing Cypress

on:
  push: 
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Install Dependencies
        run: npm install

      - name: Build SASS
        run: npm run build

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Test lint 
        run: npm run lint

      - name: Build End-To-End & Test
        run: npm run test-e2e-cli
        env:
          CYPRESS_TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          CYPRESS_TEST_PASSWORD: ${{ secrets.TEST_PASSWORD}}